# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.9"


# Sphinx setting
sphinx:
   configuration: docs/source/conf.py  # Build documentation in the docs/ directory with Sphinx
   fail_on_warning: true               # ReadtheDocs returns `Failed` during building if warning occurs

# If using Sphinx, optionally build your docs in additional formats such as PDF
formats:
   - pdf

# Optionally declare the Python requirements required to build your docs
python:
   install:
   - requirements: requirements.txt

